CREATE TABLE usuarios (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    cargo ENUM('PROPRIETARIO', 'GERENTE', 'ASSISTENTE') DEFAULT 'ASSISTENTE',
    loja_id INTEGER, 
)